=== zhangwei5095/javaman2009/trunk/HSQLDBManager1.0/src/NDot-db-Config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE ndotdb-configuration PUBLIC
	"-//SE/NDot-db-Config Configuration DTD 1.0//EN"
	"NDot-db-Config.dtd">
-->
<!ELEMENT NDot-db-Config (db*)>
<!ELEMENT db (host,dbpath,dbname)>


<!ATTLIST db port CDATA "9001" >
<!ATTLIST db silent (true|false) "true">
<!ATTLIST db trac (true|false) "false">
<!ATTLIST db tls (true|false) "false">
<!ATTLIST db no_system_exit (true|false) "false">
<!ATTLIST db id ID #REQUIRED>

<!ELEMENT host (#PCDATA)>
<!ELEMENT dbpath (#PCDATA)>
<!ELEMENT dbname (#PCDATA)>

=== zhangwei5095/javaman2009/trunk/HSQLDBManager1.0/NDot-db-Config.xml
<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE NDot-db-Config SYSTEM "src/NDot-db-Config.dtd">

<NDot-db-Config>
  <db id="001" no_system_exit="false" port="9001" silent="true" tls="false" trac="false">
    <host>localhost</host>
    <dbpath>D:\\hsqldb\\mydb\\ndotdb</dbpath>
    <dbname>ndotdb</dbname>
  </db>
  <db id="002" port="9001" silent="true" tls="false" trac="false">
    <host>www.baidu.com</host>
    <dbpath>D://dnotdb/test</dbpath>
    <dbname>test</dbname>
  </db>
  <db id="001" no_system_exit="false" port="9001" silent="true" tls="false" trac="false">
    <host>localhost</host>
    <dbpath>D:\\hsqldb\\mydb\\ndotdb</dbpath>
    <dbname>ndotdb</dbname>
  </db>
</NDot-db-Config>
